"""Add indexes on name, priority, status, due_on

Revision ID: 1ccb6223343c
Revises: d13e36295e88
Create Date: 2025-07-25 18:54:14.741448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccb6223343c'
down_revision = 'd13e36295e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_priority'))
        batch_op.drop_index(batch_op.f('ix_task_name'))
        batch_op.drop_index(batch_op.f('ix_task_due_on'))

    # ### end Alembic commands ###
